version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.13.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
