float:
  any:
    - base_args: ["@metric"]
      constructor: PGvector
      disabled: false
      docker_tag: bigvectorbench-pgvector
      module: bigvectorbench.algorithms.pgvector
      name: pgvector
      run_groups:
        M-16:
          args_groups: [{M: 16, efConstruction: 200}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
        M-24:
          arg_groups: [{M: 24, efConstruction: 200}]
          args: {}
          query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]