# # Description: This file is used to define the docker-compose configuration for the Pgvector service.
# # The default database account and password are only effective during the initial setup. 
# # If you change the account password, remember to update the database and project connection parameters.

# networks:
#   pgvector_network_cluster:
#     driver: bridge
#     name: pgvector_network_cluster

# services:
#   # db
#   pagvector:
#     image: pgvector/pgvector:0.7.4-pg16 # docker hub
#     container_name: pgvector
#     restart: always
#     command: all
#     networks:
#       - pgvector_network_cluster
#     ports:
#       - 5432:5432
#     environment:
#       # The configuration is only effective during the initial run. Changes will not take effect after restarting the image. 
#       # You need to delete the persistent data and then restart to apply the changes.
#       - POSTGRES_USER=bvb_pg
#       - POSTGRES_PASSWORD=123
#       - POSTGRES_DB=postgres
#       - POSTGRES_HOST_AUTH_METHOD=trust
#     volumes:
#       - ./pg/data:/var/lib/postgresql/data
